import type { DashboardData } from "./types"

// Demo / fallback data used when Supabase is not configured.
// Mirrors the original static dashboard seed data.
export const seedData: DashboardData = {
  sbus: [
    {
      id: "education",
      name: "Education & Child Development",
      goal: "Recurring learner-based income",
      projects: ["SmartRise Creche", "Charisma Creches", "Investhood Aftercare", "Charisma School Digitisation"],
    },
    {
      id: "technology",
      name: "Technology & Software",
      goal: "B2B contracts and software service revenue",
      projects: ["Signa LMS", "Recruitment App", "Investhood LMS", "School Systems"],
    },
    {
      id: "npo",
      name: "Youth Skills & NPO",
      goal: "Grants, sponsors, equipment and community impact",
      projects: ["Investhood Skills Hub", "SmartRise EdTech", "SOS Programmes", "Digital Innovation Programme"],
    },
    {
      id: "agro",
      name: "Agro-Tech, Camps & Community",
      goal: "Farm income, camps, events and community development",
      projects: ["Dhlamini Farm", "Coding Camps", "Robotics Camps", "School Camps", "Church Camps", "Agro-tourism"],
    },
  ],
  projects: [
    {
      id: "smartcreche",
      name: "SmartRise Creche",
      sbu: "education",
      status: "At Risk",
      priority: "High",
      owner: "Operations Manager",
      progress: 38,
      revenueTarget: "R135,000 pm",
      currentRevenue: "R1,800 pm",
      targetDate: "2026-09-01",
      nextAction: "Run direct marketing drive and parent site visits",
      risk: "Low learner registration numbers",
    },
    {
      id: "aftercare",
      name: "Investhood Aftercare",
      sbu: "education",
      status: "In Progress",
      priority: "High",
      owner: "Programme Lead",
      progress: 48,
      revenueTarget: "R120,000 pm",
      currentRevenue: "R20,000 pm",
      targetDate: "2026-07-01",
      nextAction: "Launch app and start SOS lab visits",
      risk: "Programme not fully delivering promised coding/robotics services yet",
    },
    {
      id: "signa",
      name: "Signa LMS",
      sbu: "technology",
      status: "In Progress",
      priority: "High",
      owner: "Technical Lead",
      progress: 90,
      revenueTarget: "Contract + support revenue",
      currentRevenue: "Pending approval",
      targetDate: "2026-07-01",
      nextAction: "Complete testing, payroll automation and domain migration",
      risk: "Pilot delay if testing or documentation is not signed off",
    },
    {
      id: "recruitment",
      name: "Recruitment App",
      sbu: "technology",
      status: "In Progress",
      priority: "High",
      owner: "Sales + Technical Lead",
      progress: 88,
      revenueTarget: "1 paying customer",
      currentRevenue: "Pipeline",
      targetDate: "2026-07-31",
      nextAction: "Book demos with learnership and recruitment companies",
      risk: "Insufficient sales focus after build completion",
    },
    {
      id: "sos-camps",
      name: "SOS Coding Camps",
      sbu: "npo",
      status: "On Track",
      priority: "High",
      owner: "Programme Lead",
      progress: 25,
      revenueTarget: "R50,000 - R150,000 per camp",
      currentRevenue: "Planning",
      targetDate: "2026-07-15",
      nextAction: "Publish camp calendar and send sponsor packs",
      risk: "No confirmed sponsor or registration pipeline yet",
    },
    {
      id: "farm",
      name: "Dhlamini Farm & Farm Camps",
      sbu: "agro",
      status: "In Progress",
      priority: "Medium",
      owner: "Farm Lead",
      progress: 22,
      revenueTarget: "Farm sales + camp income",
      currentRevenue: "Pre-revenue",
      targetDate: "2026-09-30",
      nextAction: "Complete access, livestock setup, first crop plan and camp concept",
      risk: "Infrastructure and operating capital constraints",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Complete SmartRise Creche curriculum and timetable",
      projectId: "smartcreche",
      owner: "BA Team",
      dueDate: "2026-06-30",
      status: "In Progress",
      priority: "High",
      progress: 55,
      notes: "Must support parent marketing and compliance.",
    },
    {
      id: "task-2",
      title: "Arrange social worker assessment for creche compliance",
      projectId: "smartcreche",
      owner: "Operations Manager",
      dueDate: "2026-06-12",
      status: "Blocked",
      priority: "High",
      progress: 20,
      notes: "Required for social development funding process.",
    },
    {
      id: "task-3",
      title: "Run weekly parent open day for SmartRise Creche",
      projectId: "smartcreche",
      owner: "Marketing Lead",
      dueDate: "2026-06-15",
      status: "Not Started",
      priority: "High",
      progress: 0,
      notes: "Saturday open day with tours and registration promotion.",
    },
    {
      id: "task-4",
      title: "Update Aftercare Management Plan",
      projectId: "aftercare",
      owner: "Programme Lead",
      dueDate: "2026-06-12",
      status: "In Progress",
      priority: "High",
      progress: 45,
      notes: "Include homework, coding, robotics, AI, computer basics and SOPs.",
    },
    {
      id: "task-5",
      title: "Schedule SOS computer lab visits",
      projectId: "aftercare",
      owner: "Operations Manager",
      dueDate: "2026-06-20",
      status: "Not Started",
      priority: "High",
      progress: 0,
      notes: "Use code.org, Investhood LMS and STEMulator.",
    },
    {
      id: "task-6",
      title: "Complete Signa payroll and timesheet automation",
      projectId: "signa",
      owner: "Technical Lead",
      dueDate: "2026-06-12",
      status: "In Progress",
      priority: "High",
      progress: 70,
      notes: "Auto-calculate days attended and generate timesheets.",
    },
    {
      id: "task-7",
      title: "Prepare Recruitment App client demo list",
      projectId: "recruitment",
      owner: "Sales Lead",
      dueDate: "2026-06-25",
      status: "In Progress",
      priority: "High",
      progress: 35,
      notes: "Target learnership, internship and recruitment companies.",
    },
    {
      id: "task-8",
      title: "Prepare SOS Coding Camp sponsor pack",
      projectId: "sos-camps",
      owner: "Programme Lead",
      dueDate: "2026-06-28",
      status: "Not Started",
      priority: "High",
      progress: 0,
      notes: "Include coding, robotics, AI and FLL camp packages.",
    },
    {
      id: "task-9",
      title: "Create Dhlamini Farm camp concept and price package",
      projectId: "farm",
      owner: "Farm Lead",
      dueDate: "2026-07-05",
      status: "Not Started",
      priority: "Medium",
      progress: 0,
      notes: "School camps, church camps, coding camps and agro-tourism.",
    },
  ],
  weeklyReview: [
    { label: "Learner growth reviewed", done: false },
    { label: "App progress reviewed", done: false },
    { label: "Demos booked and followed up", done: false },
    { label: "Sponsor pipeline updated", done: false },
    { label: "Cash flow and revenue checked", done: false },
    { label: "Top risks escalated", done: false },
    { label: "Next-week actions assigned", done: false },
  ],
  kpis: [
    { label: "Leads Captured", value: 25 },
    { label: "Follow-ups Done", value: 18 },
    { label: "Active Dev Tasks", value: 32 },
    { label: "Sponsor Follow-ups", value: 12 },
    { label: "Staff Attendance", value: "92%" },
    { label: "Cash Collected", value: "R18,450" },
    { label: "Demos Booked", value: 5 },
    { label: "Overdue Tasks", value: 0 },
  ],
  events: [],
}

export const saPublicHolidays = [
  { date: "2026-01-01", title: "New Year's Day" },
  { date: "2026-03-21", title: "Human Rights Day" },
  { date: "2026-04-03", title: "Good Friday" },
  { date: "2026-04-06", title: "Family Day" },
  { date: "2026-04-27", title: "Freedom Day" },
  { date: "2026-04-28", title: "Public Holiday: Freedom Day Observed" },
  { date: "2026-05-01", title: "Workers' Day" },
  { date: "2026-06-16", title: "Youth Day" },
  { date: "2026-08-09", title: "National Women's Day" },
  { date: "2026-08-10", title: "Public Holiday: Women's Day Observed" },
  { date: "2026-09-24", title: "Heritage Day" },
  { date: "2026-12-16", title: "Day of Reconciliation" },
  { date: "2026-12-25", title: "Christmas Day" },
  { date: "2026-12-26", title: "Day of Goodwill" },
]
